N3C.CDVIseController.InjectResource([
"On the fifth floor.",
"It's on the fifth floor.",
"It's on the fifth floor. Please use the escalator over there.",
"Yes, we do.",
"Yes, we do. Please follow me.  I'll show you.",
"Yes, we do. There are several models of Iceman. Which model would you like?",
"From ten to eight.",
"We are open from 10 a.m. to 8 p.m.",
"We are open from 10 a.m. to 8 p.m. Monday through Friday and to 9 p.m. Saturday and Sunday.",
"On Thursdays.",
"We are closed on Thursdays.",
"We are closed on the second Monday of the month.",
"I speak a little English.",
"I speak a little English. How may I help you?",
"I can speak English. And I speak Chinese, too. How may I help you?",
"All right.",
"Certainly.  Please go to the service counter.",
"Certainly.  We'll keep it at the service counter for free.",
"Yes, you can.",
"Free Wi-Fi is available around the information counter.",
"Free Wi-Fi is available around the information counter.  Here is the ID and password.",
"A wrapping cloth.",
"It's a wrapping cloth called a furoshiki. You can wrap things and carry them in it.",
"It's called a furoshiki, a traditional wrapping cloth. Many people buy them as gifts.",
"Here you are.",
"We have two types.  How do you like this one?",
"Here are some.  What color would you like?",
"Yes, this one?",
"Sure.  I'll get it for you.",
"Sure. Please feel free to take a closer look.  There are many colors.",
"Yes, we do.",
"Yes, I'll bring one size up.",
"Yes, we do.  I'll bring you a medium and a large just in case.",
"Yes, we do.  Here you are.",
"Yes, we also have it in black and gray.",
"Yes, we have it in blue and black, and also in white and red.",
"Certainly.  This way, please.",
"Certainly.  Follow me to the fitting room.",
"Certainly.  Follow me to the fitting room.  Do you have any other clothes you'd like to try on?",
"Yes, I think so.",
"Yes, it looks very nice on you.",
"Sure.  It looks very nice on you.  It gives you a bright look.",
"100% cotton.",
"This is 100% wool.",
"This is made of cotton and linen, so it's very cool.",
"No problem.",
"Sure.  I'll remove the price tag.",
"Certainly.  I'll remove the price tag.  Would you like to put the jacket that you're wearing now in a bag?",
"Yes, it is.",
"Yes, it's made in Japan.",
"Yes.  It's made in Japan using Italian fabric.",
"Yes, it is.",
"Yes, it is.  This will be a good souvenir.",
"Yes.  It has traditionally been made in this area.",
"Eight pieces.",
"There are eight pieces per box.",
"One box contains eight pieces. Each piece is packaged separately.",
"Sure.  Go ahead.",
"Yes, here you are.  How do you like it?",
"Yes, here you are.  How do you like it?  It's really popular.",
"July 10th.",
"It's best before July 10th .",
"Please eat it before July 10th.  It also needs to be refrigerated.",
"This one.",
"How about this one?  This is popular among young women in Japan.",
"If you often travel abroad, this bag is recommended.",
"I'm sorry, we can't.",
"I'm afraid we can't give any discounts.",
"No, we can't for just a purchase of one item. But if you buy two, you can get the second one half-price.",
"Thank you very much.",
"Thank you very much.  Would you like anything else?",
"Thank you very much.  Would you like to buy any other items?",
"Certainly.  A box or a bag?",
"Certainly.  Which do you prefer, a box or a bag?",
"Certainly.  Simple wrapping is free, but special wrapping costs 200 yen extra.",
"3,000 yen.",
"That'll be 3,000 yen, please.",
"That'll be 3,000 yen including tax.",
"Yes, we do.",
"Yes, we accept major credit cards.",
"Yes, we do.  Please insert your card here.",
"Yes, you can.",
"Yes.  The UnionPay Card machine is over there. Please come with me.",
"Certainly.  Please come this way.  Could you enter your PIN number?",
"No, you can't.",
"I'm sorry, but we can't change money here.",
"I'm sorry, but we can't change money if you don't buy anything.",
"Yes, we can.  Where to?",
"Yes, we can.  Where would you like them to be delivered?",
"Certainly.  Please write down the address on this form.",
"Yes, you can.",
"Yes, you can buy this item tax-free.",
"It's over 5,000 yen, so you can get it tax-free.",
"On the first floor.",
"The tax-free counter is on the first floor.  I'll guide you.",
"Please apply at the tax-free counter on the first floor.  You can receive a tax refund of 560 yen.",
"5,000 yen.",
"You have to spend 5,000 yen or more to get them tax-free.",
"Purchases of 5,000 yen or more qualify.  Please check the price excluding tax.",
"Your passport, the goods and the receipt.",
"Please take your passport, the goods and the receipt to the tax-free counter. ",
"Please take your passport, the goods and the receipt to the tax-free counter. If you used a credit card, please take that too.",
"Yes, of course.",
"I'm very sorry. I'll bring you a new one right now.",
"We're very sorry for the inconvenience. We will exchange it for a new one.  Please show me your receipt.",
"I'll check.",
"I'm sorry. Let me check.  The correct change is 2,350 yen.",
"I'm sorry. Let me check.  The amount was incorrect.  The correct change is 2,350 yen.",
"I'll check.",
"I'll check the lost and found.  What does it look like?",
"I'll check the lost and found.  Please tell me the color and size of the bag.",
"Are you all right?",
"Are you all right?  I'll guide you to the first-aid room.",
"Are you all right?  I'll guide you to the first-aid room. Can you walk?",
"＜飲食＞",
"Yes, ma'am.  How many people?",
"Certainly.  What time and how many?",
"Certainly.  What time would you like the reservation for?  May I have your name and contact information?",
"Yes, it's OK.",
"All right.  So, will that be five people, then?",
"Yes, certainly.  Your reservation will be for five people, correct?  We're looking forward to seeing you.",
"All right.  Your name, please.",
"All right.  May I have your name and the date of your reservation?",
"All right.  May I have your name and the date of your reservation?  You don't have to pay a cancellation fee.",
"Yes, we do.",
"Yes, we have private rooms for up to 10 people.",
"Yes, we have private rooms for up to 10 people.  How many people would you like a room for?",
"At six.",
"We open for dinner at six.",
"We will begin serving dinner at six.  We are serving drinks until then.",
"At 11.",
"We close at 11.",
"The last order is taken at 10 and we close at 11.",
"For 20 minutes.",
"Your table will be ready in about 20 minutes.",
"Your table will be ready in about 20 minutes.  Please sit here and wait.",
"OK.  Please sit here.",
"Certainly.  Would you like the table over there?",
"Certainly.  Please sit here.  It has a beautiful night view.",
"No, we don't.",
"I'm sorry, but we only have Japanese-style seating areas.",
"We only have Japanese-style seating areas, but you can use a chair.",
"No, you can't.",
"No.  Please take off your shoes here.",
"No.  Please take off your shoes here.  You can put your shoes on this shelf.",
"Yes, we do.",
"Here you are.  Please look at these photos of the dishes.",
"Here you are.  Please don't hesitate to ask if you have any questions.",
"No, you can't.",
"I'm sorry, but we stopped serving lunch combos at two.",
"I'm sorry, but we stopped serving lunch combos at two.  We can serve other dishes.",
"No, we don't.",
"I'm afraid we don't have any vegetarian dishes.  Can you eat eggs?",
"We don't have any vegetarian dishes, but we can prepare the dish without meat if you want.",
"The seafood dishes.",
"We recommend the seafood dishes.",
"We recommend the seafood dishes.  The assorted sashimi combo comes with rice and miso soup.",
"Sure.",
"Sure.  What would you like?",
"Sure.  May I take your drink order first?",
"Sure.  Anything else?",
"Certainly.  Will that be everything?",
"Certainly.  Would you like a combo or just that?",
"A vegetable stew.",
"This is a Japanese-style vegetable stew.  It's like borscht.",
"This is a Japanese-style vegetable stew.  This is very popular to have with beer.",
"Tuna.",
"This dish has tuna and salmon roe in it.",
"This dish has tuna and salmon roe in it.  They are on rice seasoned with vinegar.",
"All right.",
"All right.  I'll bring some extra plates.",
"All right.  I'll bring some extra plates.  Shall I divide it for you?",
"No, it doesn't.",
"No.  That costs extra.",
"No, but you can make it a combo for an extra 100 yen.",
"Yes, it is.",
"Yes, it is.  All drinks are included in this service.",
"Yes, it is.  Please keep in mind that you only have two hours for this service.",
"Sure.",
"Yes.  Please wait while I clear the table.",
"Yes.  We'll set the table.  Please wait a moment.",
"Sure.",
"Yes.  I'll bring you one.",
"Yes.  I'll bring one for you.  Please wait a second.",
"How about this sake?",
"Sweet sake goes well with this dish.  How about this one?",
"I'll show you some kinds of sake that go well with this salty dish.  I recommend this one the most.",
"OK.  Use them like this.",
"Sure.  Please hold them like this.",
"Put one within your thumb, index and middle finger, and put the other between your middle finger and ring finger.  That's good.",
"Sure.  How many?",
"Sure.  Right away.  How many glasses would you like?",
"Sure.  I'll be right back with your water.  Would you like anything else?",
"Dip it in the sauce.",
"Please dip it in the broth in the small bowl.",
"Please dip it in the broth in the small bowl.  If you'd like, please add this condiment.",
"All right.",
"Yes.  I'll put them in a to-go box for you.",
"Yes.  I'll put them in a to-go box for you.  Please eat them today.",
"Over there.",
"Please go straight, and you'll find it on your right.",
"Please go straight, and you'll find it on your right.  The one on the right is for men.",
"Certainly.  Go to the register, please.",
"Certainly.  Please pay at the register over there.",
"Certainly.  Could you bring the check with you to the register when you are ready to pay?",
"Yes.",
"Yes, you can.",
"Yes, you can.  Please insert your card into the card reader.",
"800 yen and 900 yen, please.",
"800 yen for the oyakodon and 900 yen for the katsudon, please.",
"800 yen for the oyakodon and 900 yen for the katsudon, please.  Do you each need a receipt?",
"Yes, you can.",
"Yes, you can.  It's good for a 10% discount.",
"Yes, you can.  It's good for a 10% discount.  The total is now 4,500 yen.",
"It's a service charge.",
"This is a 10% service charge.",
"This is a 10% service charge.  It covers the appetizers that were served.",
"I'm sorry.  I'll go check.",
"I'm sorry.  I'll bring it right away.",
"I'm sorry, but it's being prepared now.  Please wait a little longer.",
"Let me check.",
"I'm sorry.  Let me check the order sheet.",
"You're right.  I'll bring the correct order at once.",
"I'm sorry.",
"I'm very sorry.  We'll make you a new one right away.",
"I'm very sorry.  We'll make you a new one right away.  We'll make sure this kind of thing never happens again.",
"Let me check.",
"Let me check.  I'm sorry.  The correct total is 3,350 yen.",
"Wait a second, please.  I'll recalculate the bill.  I'm sorry.  The correct total is 3,350 yen.",
"＜鉄道＞",
"Yes.",
"Yes, it does.",
"Yes, it does.  It's the third station.",
"The Yamanote Line.",
"You should take the Yamanote Line.",
"You should take the Keihin Tohoku Line.  It's the third station.",
"At Osaki Station.",
"You should change at Shinagawa Station.",
"You should change at Shinagawa Station to the Yamanote Line.",
"At 8:20.",
"It leaves at 8:20.",
"It leaves at 8:20 from track 5.",
"Platform 10.",
"It'll leave from platform 2.",
"It'll leave from platform 2.  Go up the stairs.",
"Yes.",
"Yes, it does.",
"Yes, it does.  Ueno is the fourth station.",
"At these machines.",
"You can buy one at a ticket vending machine.",
"You can buy one at a ticket vending machine.  There are some over there.",
"Sorry, you can't.",
"I'm sorry, but you can't use this card.",
"I'm sorry, but you can't use this card.  You can buy a ticket at the ticket vending machine.",
"Exit D2.",
"Go out Exit D2.  It's over there.",
"Go out the exit over there.  Then, turn right.",
"Yes, you can.",
"Yes, you can.  But please fold it into a compact size.",
"Yes.  It's possible if you fold it into a compact size.",
"Today or another day?",
"Would you like to go today or another day?",
"Would you like to go today or another day? And would you like round-trip tickets?",
"12,000 yen.",
"It costs 12,000 yen.",
"It costs 12,000 yen.  This includes the basic fare of 9,000 yen and the super express surcharge of 3,000 yen.",
"Car No. 6.",
"The dining car is car No. 6.",
"The dining car is car No. 6.  It's open from 7 a.m. to 9 p.m.",
"No.  They're reserved.",
"No, they aren't.  The seats are reserved.",
"No, they aren't. The seats are reserved.  The next car is non-reserved.",
"Bus No. 5.",
"The bus from bus stop No. 5 goes there.",
"Bus No. 24 from bus stop No. 5 goes there.  The buses leave about every 30 minutes.",
"Go straight.",
"Go straight down this street.",
"Go straight down this street and you'll find it in front of you.",
"About five minutes.",
"It takes about five minutes on foot.",
"It takes 30 minutes on foot. It's faster to take the subway.",
"I recommend Sensoji Temple.",
"I recommend Sensoji Temple around the corner.",
"I recommend Sensoji Temple around the corner.  It's a colorful temple.",
"Near the temple.",
"Yes.  There are a lot of souvenir shops near the temple.",
"Turn right at the corner and you'll find a temple.  There are a lot of souvenir shops around there.",
"At that coffee shop.",
"You can use Wi-Fi at that coffee shop.",
"You can use Wi-Fi at that coffee shop, but it's free at the station.",
"A little.",
"I can speak a little English.",
"I can speak a little English.  Could you speak slowly?",
"Here.",
"Yes.  Here you are.",
"Yes.  Here you are.  You can keep that piece of paper.",
"A dog character.",
"It's the dog character for this region.",
"It's the dog character for this region.  It comes from an old local story.",
"It's about a Noh performance.",
"It says there is going to be a Noh performance this summer.",
"It says there is going to be a Noh performance this summer.  You will be able to see Noh outside.",
"\"Iriguchi\".",
"We read them as \"iriguchi\".",
"We read them as \"iriguchi\".  This is \"iri\" and this is \"guchi\".",
"Your ticket, please.",
"Can I see your ticket ?",
"May I see your ticket? OK.  You need a fare adjustment.  Please pay an additional fee of 30 yen.",
"From where?",
"Where did you get on the train?",
"Can you tell me where you got on the train? You have to pay the fare from that station.",
"Which train?",
"Which train line were you on?",
"Which train were you on? And also, which way was the train heading ?",
"Sure.  I'll call a taxi.",
"Sure.  I'll call a taxi right away.",
"Sure.  I'll call a taxi right away.  Please wait.",
"OK. I'll call an ambulance.",
"OK.  I'll call an ambulance immediately.",
"OK.  I'll call an ambulance immediately.  Please stay still.",
]);
